import images from "./images.json";

// Responsive image manifest generated by scripts/optimize-images.mjs.
export type ImageId = keyof typeof images;
export type ImageMeta = { role: string; width: number; height: number; widths: number[]; lqip: string };

export function image(id: ImageId): ImageMeta & { id: ImageId } {
  return { id, ...(images[id] as ImageMeta) };
}

export function srcset(id: ImageId, ext: "avif" | "webp") {
  return image(id)
    .widths.map((w) => `/media/img/${id}-${w}.${ext} ${w}w`)
    .join(", ");
}

export function fallbackSrc(id: ImageId, target = 1280) {
  const { widths } = image(id);
  const w = widths.find((x) => x >= target) ?? widths[widths.length - 1];
  return `/media/img/${id}-${w}.webp`;
}

// Video hosting: files live in /public/videos by default. To move them to a CDN,
// set VITE_MEDIA_BASE (e.g. https://cdn.example.com/radiance) — see VIDEO_HOSTING.md.
const MEDIA_BASE = (import.meta.env.VITE_MEDIA_BASE as string | undefined)?.replace(/\/$/, "") ?? "";
const v = (p: string) => `${MEDIA_BASE}/videos/${p}`;

export const videos = {
  hero: {
    webm: v("hero-1920.webm"),
    mp4: v("hero-1920.mp4"),
    mobile: v("hero-960.mp4"),
    poster: "/videos/hero-poster.webp",
  },
  film: {
    hd: v("film-1080.mp4"),
    sd: v("film-720.mp4"),
    poster: "/videos/film-poster.webp",
  },
} as const;

// Scroll-scrub frames of the tower "unveiling" (from the client's AI film).
export const scrub = {
  count: 72,
  aspect: 860 / 948,
  frame: (i: number, mobile: boolean) => `/media/scrub/${mobile ? "mobile" : "desktop"}/${String(i + 1).padStart(3, "0")}.webp`,
};

// Equirectangular preview copied out of the tour so the teaser never touches /virtual-tour/.
export const tourPreview = "/media/tour-preview.webp";
